[template]
src = "10-auth.conf.tmpl"
dest = "/etc/dovecot/conf.d/10-auth.conf"
keys = [
    "/auth/values/",
    "/auth/includes/"
]
check_cmd = "/usr/bin/doveconf -n"
reload_cmd = "/usr/sbin/service dovecot reload"