[template]
src = "15-mailboxes.conf.tmpl"
dest = "/etc/dovecot/conf.d/15-mailboxes.conf"
keys = [
    "/mailboxes/namespaces/",
    "/mailboxes/protocols/",
    "/mailboxes/plugin/",
]
check_cmd = "/usr/bin/doveconf -n"
reload_cmd = "/usr/sbin/service dovecot reload"