[template]
src = "dovecot-sql.conf.ext.tmpl"
dest = "/etc/dovecot/dovecot-sql.conf.ext"
keys = [
    "/dovecot_sql/values/",
]
check_cmd = "/usr/bin/doveconf -n"
reload_cmd = "/usr/sbin/service dovecot reload"